### ISSUE TITLE
Hi-dpi rendering in window

### ISSUE THREAD

**Issue by mdimura** [openhomm/openhomm#2]
When I start the program on hi-dpi screen in window mode, the rendering fails (see screenshot), however if I switch to full-screen - everything is OK. When I return back from full-screen - image is also fine. Rendering is also performed only in a quarter of the window when zoom level is changed.
Platforms: Ubuntu 15.10 x64, Qt 5.5.0; Win10 x64, Qt 5.5.1, migw32

![openhomm-hidpi-win](https://cloud.githubusercontent.com/assets/12734546/13027140/db41d2ea-d243-11e5-814a-acdf92038a3b.PNG)

![linux](https://cloud.githubusercontent.com/assets/12734546/13027071/47d6edbc-d241-11e5-8b6b-249fe87a636b.png)

![zoom](https://cloud.githubusercontent.com/assets/12734546/13027190/888b7db0-d245-11e5-82ac-9b9190daf450.png)

**Comment by crackedmind** [comment]
I think we need to rewrite render to use QOpenGLWidget, because QGLWidget is obsolete.

**Comment by mdimura** [comment]
This would be definitely needed at some point, but so far I fixed the problem via the devicePixelRatio() workaround, see the PR #5 .
